name: Deploy Azure SQL Infra and Restore DB

on:
  workflow_dispatch:  # Esto permite ejecutar manualmente

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Inicializar Terraform
        run: terraform init
        working-directory: infra

      - name: Validar Terraform
        run: terraform validate
        working-directory: infra

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
        working-directory: infra

  restore-db:
    runs-on: windows-latest
    needs: terraform

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Restaurar Base de Datos con PowerShell
        shell: pwsh
        run: |
          $serverName = "sqlserverdemo123.database.windows.net"
          $dbName = "demo-db"
          $username = "sqladminuser"
          $password = "YourP@ssw0rd123"
          $backupFile = "restore.sql"  # Asegúrate de tener este archivo en el repo

          Invoke-Sqlcmd -ServerInstance $serverName -Database $dbName -Username $username -Password $password -InputFile $backupFile