name: Deploy Database

on:
  push:
    paths:
      - 'infra/**'
      - 'bd.sql'
      - '.github/workflows/bd.yml'

jobs:
  deploy-db:
    runs-on: windows-latest

    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve